### ISSUE TITLE
Section links not showing section number

### ISSUE THREAD

**Issue by fxpar** [ewallah/moodle-format_masonry#3]
Hi, 

Surely I did something wrong.

The tiles are very nice (including the section summary) but activities are not showing up for user to click on:
![image](https://user-images.githubusercontent.com/11584406/27993002-f0aa80d2-64a0-11e7-95f7-acac60801a11.png)

When I click on the section title, it just refreshes the page, because the link has only the course id, but not the section number.

I am on Moodle 3.3+ (Build: 20170616)

Masonry Topics format
format_masonry | 3.32017061000
![image](https://user-images.githubusercontent.com/11584406/27992980-a7288c7e-64a0-11e7-9868-e4917b7d7718.png)
And theme:
![image](https://user-images.githubusercontent.com/11584406/27993032-790f5c22-64a1-11e7-9445-dda3e1661008.png)

Thanks for any clue on what I should be doing.
(if you'd rather like me to post this in the discussion page, just tell me)

Regards
François

**Comment by ewallah** [comment]
Hi François,

this looks related to the course layout feature that is not forced.  Can you change the course format to topics and make sure that the course layout has the "show all sections on one page" selected?
You save your changes and then change your course format back into Masonry.  This should fix the problem... 

![capture_001_09072017_213019](https://user-images.githubusercontent.com/1324161/27997014-df56453e-64ee-11e7-99d4-da68c2b746b6.png)

**Comment by fxpar** [comment]
Hi,

Your answer was very helpful.
Thank you very much. Indeed it solved nicely the problem.
Regards
François
