### ISSUE TITLE
Undefined property: stdClass::$backcolor

### ISSUE THREAD

**Issue by acquaalta** [ewallah/moodle-format_masonry#4]
Hi,

**Versions info**
Moodle: 3.7.2
MySQL: 5.7.27
PHP:  7.2.24
Theme: Boost

When debugging is set in the site settings to the maximum level, and when trying to add/remove a topic in the Masonry Topics format , I get the following message:

Notice: Undefined property: stdClass::$backcolor in /var/www/html/moodle/course/format/masonry/lib.php on line 162

![mtformat_debug_message](https://user-images.githubusercontent.com/51836675/68844481-8acfe280-06d2-11ea-8bc0-b471ebf05e6f.png)

If I click the "continue" link that can be seen in the screenshot above, a topic is added/removed.
However:

1. Since I wasn't familiar before with the topic, I don't know how the the bug (the undefined property) affects me. Can you please fix it or at least explain the effect of it?

2. I don't know if the adding/removing topic behavior that I see is the expected one - When clicking the "Add topics" link in the regular "Topics" course format, the user is asked how much topics he wants to add. Is it suppose to be the same in your format, or it's intentional that only 1 topic is added or removed?

**Comment by ewallah** [comment]
THX for the report.  Let me check if I can reproduce the error.
