### ISSUE TITLE
Unable to drag items to different places.

### ISSUE THREAD

**Issue by JosephKennedy4** [ewallah/moodle-format_masonry#5]
It is not possible to move items from one section to another; clicking on an item gives the "four pointed arrow", but the item cannot be moved.  Instead, either the cursor acts to continue selecting text on the page, or the "add a topic or add a link" dialogue box appears. 
 Double-clicking an item when the four-pointed arrow does not display the "move" dialogue.  The same behavior exists when attempting to move items within a section.

We have verified that Editing was ON when attempting to do this.

This happens in Boost, Classic, and Trema themes, on multiple devices, in the Moodle 4.0.2 environment.

**Comment by ewallah** [comment]
THX Joseph for the complete report.

I will look into it asap.

**Comment by ewallah** [comment]
Fixed in [v4.0.3](https://github.com/ewallah/moodle-format_masonry/tree/v4.0.3)
