### ISSUE TITLE
Problem with Moodle 4.0.4

### ISSUE THREAD

**Issue by ralf-krause** [ewallah/moodle-format_masonry#6]
Does the Masonry format really work with Moodle 4.0?
My Moodle is Moodle 4.0.4+ (20221007). 

My test course has 8 topics … 5 topics have names, 3 topics have none.
There are some resources and activities in the topics. You can see the hints in the cases.
But there are no links to open the resources and activities. 

The first screenshot shows the test course in Moodle 3.10, and the second screenshot shows it in Moodle 4.0.4.

![C55C0DED-FC2F-4460-85AE-9AA094BA738F](https://user-images.githubusercontent.com/27956839/194519628-ea8161fd-204e-4a67-9c40-87bc7d0a351d.jpeg)

![2F2F58DA-2156-4E1F-88FE-784C9808DD78](https://user-images.githubusercontent.com/27956839/194519706-00f32a54-b87c-438e-b23e-0c9a26b48b84.jpeg)

**Comment by ewallah** [comment]
THX for the report.

What do you see when you return to the topics format?

Hidden sections =>Hidden sections are completely invisible
Course layout =>Show all sections on one page

**Comment by ralf-krause** [comment]
<img width="522" alt="Bildschirmfoto 2022-10-08 um 15 59 36" src="https://user-images.githubusercontent.com/27956839/194711292-34beb07b-a6cf-45d7-85ca-feaebbb53527.png">


<img width="1147" alt="Bildschirmfoto 2022-10-08 um 15 58 04" src="https://user-images.githubusercontent.com/27956839/194711225-81473498-bda4-4cd3-9f0b-406ce157a4e4.png">

**Comment by ewallah** [comment]
Currently working on a new (templateless) version for Moodle 4 (https://github.com/ewallah/moodle-format_masonry/tree/test)

**Comment by ewallah** [comment]
Fixed in [v4.0.5](https://github.com/ewallah/moodle-format_masonry/releases/tag/v4.0.5)
